TITLE				Microsimulation

PROJECT_DIRECTORY			../
NET_DIRECTORY			../network/
NET_NODE_TABLE			Node.txt
NET_LINK_TABLE			Link.txt
NET_POCKET_LANE_TABLE			Pocket_Lane.txt
NET_PARKING_TABLE			Parking.txt
NET_LANE_CONNECTIVITY_TABLE		Lane_Connectivity.txt
NET_ACTIVITY_LOCATION_TABLE		Activity_Location.txt
NET_PROCESS_LINK_TABLE			Process_Link.txt
NET_UNSIGNALIZED_NODE_TABLE		Unsignalized_Node.txt
NET_SIGNALIZED_NODE_TABLE		Signalized_Node.txt
NET_TIMING_PLAN_TABLE			Timing_Plan.txt
NET_PHASING_PLAN_TABLE			Phasing_Plan.txt
NET_DETECTOR_TABLE			Detector.txt
NET_SIGNAL_COORDINATOR_TABLE		Signal_Coordinator.txt

VEHICLE_FILE			demand/Vehicle
VEHICLE_TYPE_FILE			demand/Vehicle_Type.txt

PLAN_FILE             			plan/TimePlan
NODE_LIST_PATHS			YES

CELL_SIZE				7.5
TIME_STEPS_PER_SECOND			1
TIME_OF_DAY_FORMAT			24_HOUR_CLOCK
SIMULATION_START_TIME			0:00
SIMULATION_END_TIME			27:00

SPEED_CALCULATION_METHOD		CELL-BASED

DRIVER_REACTION_TIME			0.7
SLOW_DOWN_PROBABILITY			20
SLOW_DOWN_PERCENTAGE			0
RANDOM_NUMBER_SEED          		1122687672

PLAN_FOLLOWING_DISTANCE			525
LOOK_AHEAD_DISTANCE			260
LOOK_AHEAD_TIME_FACTOR			1.0
LOOK_AHEAD_LANE_FACTOR			4.0
MAXIMUM_SWAPPING_SPEED			37.5
MAXIMUM_SPEED_DIFFERENCE		7.5
ENFORCE_PARKING_LANES			Yes

MINIMUM_WAITING_TIME			120
MAXIMUM_WAITING_TIME			3600
MAX_ARRIVAL_TIME_VARIANCE		180
MAX_DEPARTURE_TIME_VARIANCE		180

NEW_PROBLEM_FILE			results/Msim_Problem
MAX_SIMULATION_PROBLEMS			100000

OUTPUT_SUMMARY_FILE_1		results/LinkDelay.txt
OUTPUT_SUMMARY_FORMAT_1		TAB_DELIMITED
OUTPUT_SUMMARY_INCREMENT_1		${inc}
OUTPUT_SUMMARY_TIME_RANGE_1		${a}..86400

OUTPUT_SUMMARY_FILE_2		results/Performance.txt
OUTPUT_SUMMARY_TIME_FORMAT_2		24_HOUR_CLOCK
OUTPUT_SUMMARY_INCREMENT_2		0:15
OUTPUT_SUMMARY_TIME_RANGE_2		0:00..27:00

OUTPUT_EVENT_TYPE_1			RUN_TIME
OUTPUT_EVENT_FILE_1			results/Event.txt
OUTPUT_EVENT_FORMAT_1		TAB_DELIMITED
OUTPUT_EVENT_TIME_FORMAT_1		SECONDS

OUTPUT_OCCUPANCY_FILE_1		results/Occupancy_Avg.txt
OUTPUT_OCCUPANCY_TIME_FORMAT_1	24_HOUR_CLOCK
OUTPUT_OCCUPANCY_INCREMENT_1		0:15
OUTPUT_OCCUPANCY_TIME_RANGE_1		0..27:00
OUTPUT_OCCUPANCY_MAX_FLAG_1		NO

OUTPUT_SPEED_FILE_1			results/Speed_Bins.txt
OUTPUT_SPEED_FORMAT_1		TAB_DELIMITED
OUTPUT_SPEED_FILTER_1		1
OUTPUT_SPEED_TIME_FORMAT_1		24_HOUR_CLOCK
#OUTPUT_SPEED_INCREMENT_1		0:15
#OUTPUT_SPEED_TIME_RANGE_1		0..30:00
#OUTPUT_SPEED_LINK_RANGE_1		1..10
OUTPUT_SPEED_SAMPLE_TIME_1		1
OUTPUT_SPEED_BOX_LENGTH_1		0
OUTPUT_SPEED_NUM_BINS_1		6
