TITLE                    Merge Plan Files

PROJECT_DIRECTORY		 ../plan

INPUT_PLAN_FILE          RetainPlan
MERGE_PLAN_FILE          PreviousPlan
OUTPUT_PLAN_FILE         Plan

PLANPREP_REPORT_1     PERCENT_PATH_CHANGE
PLANPREP_REPORT_2     PERCENT_TRAVEL_TIME_CHANGE
PLAN_SORT_OPTION	  TRAVELER
