TITLE                      Compare Plan Travel Times

PROJECT_DIRECTORY			../plan

INPUT_PLAN_FILE            NewPlan
COMPARE_PLAN_FILE          PreviousPlan
OUTPUT_PLAN_FILE           RetainPlan

PERCENT_TIME_DIFFERENCE    10
MINIMUM_TIME_DIFFERENCE    2
MAXIMUM_TIME_DIFFERENCE    30
SELECTION_PERCENTAGE       50
MAXIMUM_PERCENT_SELECTED   ${inc}

SELECT_BY_PERCENT_DIFFERENCE	YES

RANDOM_NUMBER_SEED	78910
